server:
  port: 8880
#debug: true
#logging:
#  level: trace
spring:
  profiles:
    active: dev
  application:
    name: helloService
endpoints:
  shutdown:
    enabled: true
management:
  security:
    enabled: false
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka/